version: "3.8"

services:
  mongodb:
    profiles: ["local", "local-ext", "cloud"]
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    volumes:
      - ${HOME}/DOCKER_DATA/mongodb:/data/db
      - ${HOME}/pipeline_datalake:/pipeline_datalake
    env_file:
      - ${HOME}/.docker_pipeline.env
    networks:
      - concept-network

  ontology-svc:
    profiles: ["local", "local-ext", "cloud"]
    build:
      context: ./docker/ontology-svc
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ${HOME}/pipeline_datalake:/pipeline_datalake
    env_file:
      - ${HOME}/.docker_pipeline.env
    depends_on:
      - mongodb
    networks:
      - concept-network

  ollama:
    profiles: ["local-ext"]
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/DOCKER_DATA/ollama:/root/.ollama
      - ${HOME}/pipeline_datalake:/pipeline_datalake
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 16G
        reservations:
          cpus: "2"
          memory: 8G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - concept-network
    restart: unless-stopped

  miniconda:
    profiles: ["local", "local-ext"]
    build:
      context: ./docker/miniconda
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ${HOME}/pipeline_datalake:/pipeline_datalake
      - ./notebooks:/app/notebooks
    env_file:
      - ${HOME}/.docker_pipeline.env
    environment:
      - JUPYTER_TOKEN=develop
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - concept-network
    restart: unless-stopped

networks:
  concept-network:
    driver: bridge
